services:
  postgresql:
    image: postgres:16
    container_name: author_service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 232323
      POSTGRES_DB: author-service
    volumes:
      - ./order-data:/var/lib/postgresql/data
