services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic232323  # Burada istediğiniz şifreyi kullanabilirsiniz
    ports:
      - "9200:9200"  # Elasticsearch'e erişim portu
      - "9300:9300"  # Elasticsearch node-to-node iletişim portu
    networks:
      - elastic_network
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Verilerin kalıcı olması için volume ekleniyor

volumes:
  esdata:
    driver: local

networks:
  elastic_network:
    driver: bridge