services:
  postgresql:
    image: postgres:16
    container_name: category_postgres
    ports:
      - "${DB_PORT_EXTERNAL:-5437}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bookstore-network

  category-service:
    image: category-service:latest
    container_name: category-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRINGDOC_SWAGGER-UI_ENABLED=${SWAGGER_ENABLED}
    depends_on:
      - postgresql
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data:
